# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
    date = "2021-04-20";
  };
  swhkd = {
    pname = "swhkd";
    version = "ddada68da7feeef26acad47ec4194c6315b4fccb";
    src = fetchFromGitHub {
      owner = "waycrate";
      repo = "swhkd";
      rev = "ddada68da7feeef26acad47ec4194c6315b4fccb";
      fetchSubmodules = false;
      sha256 = "sha256-JV/fUnS+7EsyrthEs3ABUBN291VUPjnKG1GsmrG53vI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./swhkd-ddada68da7feeef26acad47ec4194c6315b4fccb/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2023-06-30";
  };
}
