# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  aliyunpan = {
    pname = "aliyunpan";
    version = "0edf7d0af277d16961f2b366183d74d4a419efda";
    src = fetchFromGitHub {
      owner = "tickstep";
      repo = "aliyunpan";
      rev = "0edf7d0af277d16961f2b366183d74d4a419efda";
      fetchSubmodules = false;
      sha256 = "sha256-Vxr7H6Y77WWMHu7vxLptRlOodK7iidaBTjSivY4WgzI=";
    };
    date = "2023-04-30";
  };
  gtk3-nocsd = {
    pname = "gtk3-nocsd";
    version = "512c2bd866d71def6ffd4d85ca98ae12fe989c62";
    src = fetchFromGitHub {
      owner = "ZaWertun";
      repo = "gtk3-nocsd";
      rev = "512c2bd866d71def6ffd4d85ca98ae12fe989c62";
      fetchSubmodules = false;
      sha256 = "sha256-BOsQqxaVdC5O6EnB3KZinKSj0U5mCcX8HSjRmSBUFks=";
    };
    date = "2021-06-23";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
    date = "2021-04-20";
  };
  mpv-iptvplus = {
    pname = "mpv-iptvplus";
    version = "e4fde04bbad4573b94695df6409edf6e88ecdb3c";
    src = fetchFromGitHub {
      owner = "pintassilgo";
      repo = "mpv-iptvplus";
      rev = "e4fde04bbad4573b94695df6409edf6e88ecdb3c";
      fetchSubmodules = false;
      sha256 = "sha256-+LTp2eTVow+ib0/+8YZkxZ+X4LI8bFxT/i05XeEFBx8=";
    };
    date = "2023-01-04";
  };
  swhkd = {
    pname = "swhkd";
    version = "2e6f091817be5f6ebf837f8fc1cdf1e54f0b3526";
    src = fetchFromGitHub {
      owner = "waycrate";
      repo = "swhkd";
      rev = "2e6f091817be5f6ebf837f8fc1cdf1e54f0b3526";
      fetchSubmodules = false;
      sha256 = "sha256-6kTRAUP///EwIkF1QkQByHqHW55u2L2Gv3c+B5z3e5U=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./swhkd-2e6f091817be5f6ebf837f8fc1cdf1e54f0b3526/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2023-07-29";
  };
  wallpaper-engine-kde-plugin = {
    pname = "wallpaper-engine-kde-plugin";
    version = "f972b2a24c9c3cc2d3e4f41d2ebd14f1473cebdf";
    src = fetchFromGitHub {
      owner = "catsout";
      repo = "wallpaper-engine-kde-plugin";
      rev = "f972b2a24c9c3cc2d3e4f41d2ebd14f1473cebdf";
      fetchSubmodules = true;
      sha256 = "sha256-BVtTnJA1RLUU/Tj7WI/80ja4pI8NezHCjKvB72VjrZk=";
    };
    date = "2023-08-06";
  };
}
