# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  aliyunpan = {
    pname = "aliyunpan";
    version = "0edf7d0af277d16961f2b366183d74d4a419efda";
    src = fetchFromGitHub {
      owner = "tickstep";
      repo = "aliyunpan";
      rev = "0edf7d0af277d16961f2b366183d74d4a419efda";
      fetchSubmodules = false;
      sha256 = "sha256-Vxr7H6Y77WWMHu7vxLptRlOodK7iidaBTjSivY4WgzI=";
    };
    date = "2023-04-30";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
    date = "2021-04-20";
  };
  swhkd = {
    pname = "swhkd";
    version = "2e6f091817be5f6ebf837f8fc1cdf1e54f0b3526";
    src = fetchFromGitHub {
      owner = "waycrate";
      repo = "swhkd";
      rev = "2e6f091817be5f6ebf837f8fc1cdf1e54f0b3526";
      fetchSubmodules = false;
      sha256 = "sha256-6kTRAUP///EwIkF1QkQByHqHW55u2L2Gv3c+B5z3e5U=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./swhkd-2e6f091817be5f6ebf837f8fc1cdf1e54f0b3526/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2023-07-29";
  };
}
